const sId = {}

sId['UNKNOWN:S-G-UCIZ--'] = ['UNKNOWN:GR.IC.FF.INFANTRY', 'GR.IC.ARMOUR']
sId['FRIEND:S-G-UCIZ--'] = ['FRIEND:GR.IC.FF.INFANTRY', 'GR.IC.ARMOUR']
sId['NEUTRAL:S-G-UCIZ--'] = ['NEUTRAL:GR.IC.FF.INFANTRY', 'GR.IC.ARMOUR']
sId['HOSTILE:S-G-UCIZ--'] = ['HOSTILE:GR.IC.FF.INFANTRY', 'GR.IC.ARMOUR']
sId['UNKNOWN:S-G-USM---'] = ['UNKNOWN:GR.IC.FF.MEDICAL']
sId['FRIEND:S-G-USM---'] = ['FRIEND:GR.IC.FF.MEDICAL']
sId['NEUTRAL:S-G-USM---'] = ['NEUTRAL:GR.IC.FF.MEDICAL']
sId['HOSTILE:S-G-USM---'] = ['HOSTILE:GR.IC.FF.MEDICAL']

export default sId
